Repository Chocobozzz/PeerTube, pull requests merged in 2020-07, with the labels that each got.

#2924 simplify navigation within most admin menus
  client/src/app/+admin/admin.component.html
  client/src/app/+admin/admin.component.scss
  client/src/app/+admin/admin.component.ts
  client/src/app/+admin/follows/follows.component.html
  client/src/app/+admin/moderation/moderation.component.html
  client/src/app/+admin/moderation/moderation.component.ts
  client/src/app/+my-account/my-account.component.ts
  client/src/app/+my-account/my-account.module.ts
  client/src/app/shared/shared-icons/global-icon.component.ts
  client/src/app/shared/shared-main/misc/index.ts
  client/src/app/shared/shared-main/misc/top-menu-dropdown.component.html
  client/src/app/shared/shared-main/misc/top-menu-dropdown.component.scss
  client/src/app/shared/shared-main/misc/top-menu-dropdown.component.ts
  client/src/app/shared/shared-main/shared-main.module.ts
  client/src/assets/images/feather/log-in.svg
Labels: UI

#2897 Add ability to override client assets : logo - favicon - PWA icons - PWA manifest name and description
  client/src/app/app.component.scss
  client/src/index.html
  config/default.yaml
  config/production.yaml.example
  config/test-1.yaml
  config/test-2.yaml
  config/test-3.yaml
  config/test-4.yaml
  config/test-5.yaml
  config/test-6.yaml
  server/controllers/client.ts
  server/initializers/config.ts
  server/initializers/constants.ts
  server/lib/client-html.ts
  support/docker/production/config/production.yaml
Labels: Type: Discussion :thought_balloon:, UI

#2963 correct maximized icon padding since new icons set implemented
  client/src/app/shared/shared-forms/markdown-textarea.component.scss
Labels: UI

#2962 disable vertical scroll instead of hide on desktop browsers
  client/src/sass/application.scss
  client/src/sass/bootstrap.scss
Labels: UI

#2977 Update my-account sub-menus icons
  client/src/app/+admin/admin.component.ts
  client/src/app/+my-account/my-account.component.ts
  client/src/app/shared/shared-icons/global-icon.component.ts
  client/src/assets/images/feather/server.svg
  client/src/assets/images/feather/user-x.svg
  client/src/assets/images/misc/peertube-x.svg
  scripts/generate-code-contributors.ts
Labels: UI

#2971 Improve navigation sub-menu and tabs effects
  client/src/app/+admin/admin.component.scss
  client/src/app/+admin/follows/followers-list/followers-list.component.html
  client/src/app/+admin/follows/following-list/following-list.component.html
  client/src/app/+admin/follows/video-redundancies-list/video-redundancies-list.component.html
  client/src/app/+admin/moderation/abuse-list/abuse-list.component.html
  client/src/app/+admin/moderation/video-block-list/video-block-list.component.html
  client/src/app/+admin/plugins/plugins.component.html
  client/src/app/+admin/plugins/plugins.component.scss
  client/src/app/+admin/system/system.component.html
  client/src/app/+my-account/+my-account-video-channels/my-account-video-channels.component.html
  client/src/app/+my-account/my-account-history/my-account-history.component.html
  client/src/app/+my-account/my-account-ownership/my-account-ownership.component.html
  client/src/app/+my-account/my-account-subscriptions/my-account-subscriptions.component.html
  client/src/app/+my-account/my-account-video-imports/my-account-video-imports.component.html
  client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.html
  client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.scss
  client/src/app/+my-account/my-account-videos/my-account-videos.component.html
  client/src/app/+my-account/my-account-videos/my-account-videos.component.scss
  client/src/app/+my-account/my-account.component.scss
  client/src/app/+videos/+video-edit/video-add.component.scss
  client/src/app/shared/shared-main/misc/top-menu-dropdown.component.html
  client/src/app/shared/shared-main/misc/top-menu-dropdown.component.scss
  client/src/app/shared/shared-main/misc/top-menu-dropdown.component.ts
  client/src/app/shared/shared-moderation/account-blocklist.component.html
  client/src/app/shared/shared-moderation/server-blocklist.component.html
  client/src/sass/application.scss
  client/src/sass/bootstrap.scss
  client/src/sass/include/_mixins.scss
  client/src/sass/include/_variables.scss
Labels: UI

#2988 Hide generic channel display name and avatar on watch view
  client/src/app/+videos/+video-watch/video-watch.component.html
  client/src/app/+videos/+video-watch/video-watch.component.scss
  client/src/app/+videos/+video-watch/video-watch.component.ts
  client/src/app/shared/shared-main/account/avatar.component.html
  client/src/app/shared/shared-main/account/avatar.component.ts
Labels: Status: Waiting changes, UI

#2981 Display user quota progress bars above upload form
  client/src/app/+my-account/my-account-settings/my-account-settings.component.html
  client/src/app/+my-account/my-account-settings/my-account-settings.component.scss
  client/src/app/+my-account/my-account-settings/my-account-settings.component.ts
  client/src/app/+videos/+video-edit/video-add.component.html
  client/src/app/+videos/+video-edit/video-add.component.scss
  client/src/app/+videos/+video-edit/video-add.component.ts
  client/src/app/shared/shared-main/shared-main.module.ts
  client/src/app/shared/shared-main/users/index.ts
  client/src/app/shared/shared-main/users/user-quota.component.html
  client/src/app/shared/shared-main/users/user-quota.component.scss
  client/src/app/shared/shared-main/users/user-quota.component.ts
Labels: Status: Waiting answer, UI

#3004 correct regressions on sub-menu for account and admin
  client/src/app/shared/shared-main/misc/top-menu-dropdown.component.scss
  client/src/sass/application.scss
Labels: Priority: High, UI

#3012 Switch examples to curl since httpie has a 512MB limit
  support/doc/api/openapi.yaml
Labels: Component: Documentation :books:

#2966 Add alert and hide upload view when no upload is possible
  client/src/app/+admin/admin.component.ts
  client/src/app/+my-account/my-account.component.ts
  client/src/app/+videos/+video-edit/video-add.component.html
  client/src/app/+videos/+video-edit/video-add.component.scss
  client/src/app/+videos/+video-edit/video-add.component.ts
  client/src/app/core/auth/auth-user.model.ts
  client/src/app/core/users/user.model.ts
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.ts
  client/src/app/shared/shared-main/misc/top-menu-dropdown.component.html
  client/src/app/shared/shared-main/misc/top-menu-dropdown.component.ts
Labels: Status: Waiting changes, UI

#2996 Add fcbk open-graph and twitter-card metas for accounts, video-channels, playlists urls
  server/controllers/client.ts
  server/lib/client-html.ts
  server/models/video/video-playlist.ts
  server/tests/client.ts
Labels: Status: Waiting changes

#2980 Improve (accessibility title) and move action-buttons on left in tables
  client/src/app/+admin/follows/followers-list/followers-list.component.html
  client/src/app/+admin/follows/following-list/following-list.component.html
  client/src/app/+admin/follows/video-redundancies-list/video-redundancies-list.component.html
  client/src/app/+admin/moderation/instance-blocklist/instance-account-blocklist.component.html
  client/src/app/+admin/users/user-list/user-list.component.html
  client/src/app/+my-account/+my-account-video-channels/my-account-video-channels.component.html
  client/src/app/+my-account/my-account-ownership/my-account-ownership.component.html
  client/src/app/+my-account/my-account-video-imports/my-account-video-imports.component.html
  client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.html
  client/src/app/+my-account/my-account-videos/my-account-videos.component.html
  client/src/app/shared/shared-main/buttons/button.component.html
  client/src/app/shared/shared-main/buttons/button.component.scss
  client/src/app/shared/shared-main/buttons/delete-button.component.html
  client/src/app/shared/shared-main/buttons/delete-button.component.ts
  client/src/app/shared/shared-main/buttons/edit-button.component.html
  client/src/app/shared/shared-main/buttons/edit-button.component.ts
  client/src/app/shared/shared-moderation/account-blocklist.component.html
  client/src/app/shared/shared-moderation/server-blocklist.component.html
  client/src/app/shared/shared-moderation/user-moderation-dropdown.component.ts
Labels: Status: Waiting answer, Status: Waiting changes, UI
