Repository Chocobozzz/PeerTube, pull requests merged in 2020-05, with the labels that each got.

#2695 Fix tables width, paginators, button on mobile / touchscreens
  client/src/app/+my-account/my-account.component.scss
  client/src/app/shared/buttons/action-dropdown.component.html
  client/src/sass/application.scss
  client/src/sass/bootstrap.scss
  client/src/sass/include/_bootstrap-variables.scss
  client/src/sass/primeng-custom.scss
Labels: UI

#2706 Fix dropdown-user placement and menu-left scroll on touchscreens
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.scss
  client/src/app/menu/menu.component.ts
Labels: UI

#2737 Use video abuse filters on client side
  client/src/app/+admin/moderation/video-abuse-list/video-abuse-list.component.html
  client/src/app/shared/rest/rest.service.ts
  client/src/app/shared/video-abuse/video-abuse.service.ts
  server/controllers/api/videos/abuse.ts
  server/helpers/custom-validators/video-abuses.ts
  server/middlewares/validators/videos/video-abuses.ts
  server/models/utils.ts
  server/models/video/video-abuse.ts
  server/tests/api/check-params/video-abuses.ts
  server/tests/api/users/users.ts
  server/tests/api/videos/video-abuse.ts
  shared/extra-utils/videos/video-abuses.ts
  shared/models/videos/abuse/video-abuse-video-is.type.ts
Labels: Type: Maintenance :construction_worker_woman:

#2707 Fix regression my-account menu overflow-x on screen width < 800px
  client/src/app/core/menu/menu.service.ts
  client/src/app/shared/menu/top-menu-dropdown.component.html
  client/src/app/shared/menu/top-menu-dropdown.component.ts
  client/src/app/shared/misc/screen.service.ts
  client/src/sass/application.scss
Labels: UI

#2711 Fix non-fixed header and menu when overflow-x body on touchscreens
  client/src/app/+my-account/my-account-video-channels/my-account-video-channels.component.html
  client/src/app/+my-account/my-account-video-channels/my-account-video-channels.component.scss
  client/src/app/+my-account/my-account-videos/my-account-videos.component.html
  client/src/app/+my-account/my-account-videos/my-account-videos.component.scss
  client/src/app/search/search.component.scss
Labels: UI

#2538 Fixes docker-compose .env
  support/doc/docker.md
  support/docker/production/.env
Labels: Component: Docker :whale:

#2792 Filter comments from muted accounts/instances
  server/controllers/activitypub/client.ts
  server/controllers/api/videos/comment.ts
  server/lib/activitypub/process/process-create.ts
  server/lib/blocklist.ts
  server/lib/notifier.ts
  server/models/account/account.ts
  server/models/utils.ts
  server/models/video/video-abuse.ts
  server/models/video/video-comment.ts
  server/tests/api/users/blocklist.ts
  server/tests/api/videos/multiple-servers.ts
  server/tests/feeds/feeds.ts
  shared/extra-utils/videos/video-comments.ts
  shared/extra-utils/videos/videos.ts
Labels: Component: Moderation :godmode:
