Repository Chocobozzz/PeerTube, pull requests merged in 2020-03, with the labels that each got.

#2530 Add Nginx configuration to redirect videos to their CDN location
  support/nginx/peertube
Labels: Status: Requires Tests

#2542 Servicify menu, close menu on admin for medium screens
  client/src/app/app-routing.module.ts
  client/src/app/app.component.html
  client/src/app/app.component.ts
  client/src/app/core/core.module.ts
  client/src/app/core/menu/index.ts
  client/src/app/core/menu/menu.service.ts
  client/src/app/core/routing/index.ts
  client/src/app/core/routing/menu-guard.service.ts
  client/src/app/core/theme/theme.service.ts
  client/src/app/shared/misc/screen.service.ts
Labels: UI

#2546 Settings and administration panels design rebalancing: grid, colors, font-{size, weight}
  client/src/app/+about/about.component.html
  client/src/app/+admin/admin.component.html
  client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html
  client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.scss
  client/src/app/+admin/plugins/shared/toggle-plugin-type.scss
  client/src/app/+my-account/my-account-settings/my-account-change-email/my-account-change-email.component.scss
  client/src/app/+my-account/my-account-settings/my-account-change-password/my-account-change-password.component.scss
  client/src/app/+my-account/my-account-settings/my-account-danger-zone/my-account-danger-zone.component.html
  client/src/app/+my-account/my-account-settings/my-account-interface/my-account-interface-settings.component.scss
  client/src/app/+my-account/my-account-settings/my-account-profile/my-account-profile.component.html
  client/src/app/+my-account/my-account-settings/my-account-profile/my-account-profile.component.scss
  client/src/app/+my-account/my-account-settings/my-account-settings.component.html
  client/src/app/+my-account/my-account-settings/my-account-settings.component.scss
  client/src/app/+my-account/my-account-settings/my-account-video-settings/my-account-video-settings.component.scss
  client/src/app/+my-account/shared/actor-avatar-info.component.ts
  client/src/app/shared/forms/markdown-textarea.component.scss
  client/src/app/shared/menu/top-menu-dropdown.component.html
  client/src/sass/application.scss
  client/src/sass/bootstrap.scss
  client/src/sass/include/_mixins.scss
  config/default.yaml
  server/tests/api/server/config.ts
  server/tests/client.ts
Labels: UI

#2567 Change raw.github.com to raw.githubusercontent.com
  support/doc/docker.md
Labels: Component: Documentation :books:

#2558 Add overview of a user's actions in user-edit
  client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html
  client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.scss
  client/src/app/+admin/users/user-edit/user-create.component.ts
  client/src/app/+admin/users/user-edit/user-edit.component.html
  client/src/app/+admin/users/user-edit/user-edit.component.scss
  client/src/app/+admin/users/user-edit/user-edit.ts
  client/src/app/+admin/users/user-edit/user-password.component.ts
  client/src/app/+admin/users/user-edit/user-update.component.ts
  client/src/app/+my-account/my-account.module.ts
  client/src/app/+my-account/shared/actor-avatar-info.component.html
  client/src/app/shared/shared.module.ts
  client/src/app/shared/users/user.model.ts
  client/src/app/shared/users/user.service.ts
  client/src/app/shared/video/modals/video-report.component.html
  client/src/sass/include/_mixins.scss
  server/middlewares/validators/users.ts
  server/models/account/user.ts
  server/tests/api/users/users.ts
  shared/extra-utils/users/users.ts
  shared/models/users/user.model.ts
Labels: Component: Moderation :godmode:, UI
