Repository Chocobozzz/PeerTube, pull requests merged in 2020-02, with the labels that each got.

#2460 Add ListOverflow component to prevent sub-menu overflow
  client/src/app/+about/about-instance/contact-admin-modal.component.ts
  client/src/app/+accounts/accounts.component.html
  client/src/app/+accounts/accounts.component.ts
  client/src/app/+admin/admin.component.html
  client/src/app/+admin/admin.component.ts
  client/src/app/+admin/moderation/video-abuse-list/moderation-comment-modal.component.ts
  client/src/app/+my-account/my-account-ownership/my-account-accept-ownership/my-account-accept-ownership.component.ts
  client/src/app/+my-account/my-account-videos/video-change-ownership/video-change-ownership.component.ts
  client/src/app/+video-channels/video-channels.component.html
  client/src/app/+video-channels/video-channels.component.ts
  client/src/app/menu/language-chooser.component.ts
  client/src/app/modal/instance-config-warning-modal.component.ts
  client/src/app/modal/welcome-modal.component.ts
  client/src/app/shared/misc/list-overflow.component.html
  client/src/app/shared/misc/list-overflow.component.scss
  client/src/app/shared/misc/list-overflow.component.ts
  client/src/app/shared/moderation/user-ban-modal.component.ts
  client/src/app/shared/shared.module.ts
  client/src/app/shared/video/modals/video-blacklist.component.ts
  client/src/app/shared/video/modals/video-download.component.ts
  client/src/app/shared/video/modals/video-report.component.ts
  client/src/app/videos/+video-edit/shared/video-caption-add-modal.component.ts
  client/src/app/videos/+video-watch/modal/video-share.component.ts
  client/src/app/videos/+video-watch/modal/video-support.component.ts
  client/src/sass/application.scss
  client/src/sass/bootstrap.scss
Labels: Component: Mobile, UI

#2503 Explain view calculation on short videos, rewording
  FAQ.md
Labels: Component: Documentation :books:

#2507 Mark additional strings as translatable
  client/src/app/+admin/plugins/plugin-list-installed/plugin-list-installed.component.html
  client/src/app/+admin/system/logs/logs.component.html
  client/src/app/+my-account/my-account-history/my-account-history.component.html
  client/src/app/app.component.html
  client/src/app/login/login.component.html
  client/src/app/modal/instance-config-warning-modal.component.html
  client/src/app/shared/instance/instance-features-table.component.html
  client/src/app/shared/video-playlist/video-add-to-playlist.component.html
Labels: Component: i18n :abcd:

#2494 Chore/docker-documentation-improvements
  support/doc/docker.md
  support/docker/production/.env
  support/docker/production/config/traefik.toml
  support/docker/production/docker-compose.yml
Labels: Component: Docker :whale:, Component: Documentation :books:

#2514 Add visitor settings, rework logged-in dropdown
  CREDITS.md
  client/src/app/+about/about-instance/about-instance.component.html
  client/src/app/+accounts/account-videos/account-videos.component.ts
  client/src/app/+my-account/my-account-history/my-account-history.component.ts
  client/src/app/+my-account/my-account-settings/my-account-interface/my-account-interface-settings.component.html
  client/src/app/+my-account/my-account-settings/my-account-interface/my-account-interface-settings.component.ts
  client/src/app/+my-account/my-account-settings/my-account-video-settings/my-account-video-settings.component.html
  client/src/app/+my-account/my-account-settings/my-account-video-settings/my-account-video-settings.component.ts
  client/src/app/+my-account/my-account.component.html
  client/src/app/+my-account/my-account.module.ts
  client/src/app/+video-channels/video-channel-videos/video-channel-videos.component.ts
  client/src/app/app.component.html
  client/src/app/app.module.ts
  client/src/app/core/auth/auth-user.model.ts
  client/src/app/core/theme/theme.service.ts
  client/src/app/menu/language-chooser.component.scss
  client/src/app/menu/language-chooser.component.ts
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.scss
  client/src/app/menu/menu.component.ts
  client/src/app/modal/quick-settings-modal.component.html
  client/src/app/modal/quick-settings-modal.component.scss
  client/src/app/modal/quick-settings-modal.component.ts
  client/src/app/shared/images/global-icon.component.ts
  client/src/app/shared/misc/help.component.scss
  client/src/app/shared/misc/storage.service.ts
  client/src/app/shared/shared.module.ts
  client/src/app/shared/users/user.model.ts
  client/src/app/shared/users/user.service.ts
  client/src/app/shared/video/abstract-video-list.ts
  client/src/app/shared/video/video.service.ts
  client/src/app/shared/video/videos-selection.component.ts
  client/src/app/videos/+video-watch/video-watch-playlist.component.ts
  client/src/app/videos/+video-watch/video-watch.component.html
  client/src/app/videos/+video-watch/video-watch.component.scss
  client/src/app/videos/+video-watch/video-watch.component.ts
  client/src/app/videos/+video-watch/video-watch.module.ts
  client/src/app/videos/recommendations/recommended-videos.component.html
  client/src/app/videos/recommendations/recommended-videos.component.scss
  client/src/app/videos/recommendations/recommended-videos.component.ts
  client/src/app/videos/video-list/video-local.component.ts
  client/src/app/videos/video-list/video-most-liked.component.ts
  client/src/app/videos/video-list/video-recently-added.component.ts
  client/src/app/videos/video-list/video-trending.component.ts
  client/src/app/videos/video-list/video-user-subscriptions.component.ts
  client/src/assets/images/global/video-lang.svg
  client/src/assets/images/menu/about.svg
  client/src/assets/images/menu/administration.svg
  client/src/assets/images/menu/eye-closed.svg
  client/src/assets/images/menu/eye.svg
  client/src/assets/images/menu/language.png
  client/src/assets/images/menu/language.svg
  client/src/assets/images/menu/moonsun.svg
  client/src/assets/images/menu/p2p.svg
  client/src/sass/application.scss
  client/src/sass/bootstrap.scss
  client/src/sass/include/_mixins.scss
  client/src/sass/include/_variables.scss
  client/src/sass/primeng-custom.scss
Labels: UI
