Repository Chocobozzz/PeerTube, pull requests merged in 2020-11, with the labels that each got.

#3246 Update FAQ.md wrt performance estimates and strategies
  FAQ.md
Labels: Component: Documentation :books:

#3255 render html/markdown for new comment notification email
  client/package.json
  client/yarn.lock
  package.json
  server/lib/emailer.ts
  server/lib/emails/video-comment-mention/html.pug
  server/lib/emails/video-comment-new/html.pug
  yarn.lock
Labels: Component: Notifications, Component: Security

#3288 fix link in dependencies version guide
  support/doc/dependencies.md
Labels: Component: Documentation :books:

#3305 fix CONTRIBUTING.md command order
  .github/CONTRIBUTING.md
Labels: Component: Documentation :books:

#3313 refresh nginx config and optimize delivery
  README.md
  support/nginx/peertube
Labels: Type: Maintenance :construction_worker_woman:

#3311 default youtube-dl to use ipv4
  config/default.yaml
  config/production.yaml.example
  server/helpers/youtube-dl.ts
  server/initializers/config.ts
Labels: Component: CLI, Component: Import

#3363 add My History API to openapi
  support/doc/api/openapi.yaml
Labels: Component: Documentation :books:
