Repository Chocobozzz/PeerTube, pull requests merged in 2020-12, with the labels that each got.

#3357 Improvements login and sign-up pages UX/UI
  client/src/app/+login/login.component.html
  client/src/app/+login/login.component.scss
  client/src/app/+login/login.component.ts
  client/src/app/+login/login.module.ts
  client/src/app/+signup/+register/custom-stepper.component.html
  client/src/app/+signup/+register/custom-stepper.component.scss
  client/src/app/+signup/+register/custom-stepper.component.ts
  client/src/app/+signup/+register/register-step-terms.component.html
  client/src/app/+signup/+register/register-step-terms.component.ts
  client/src/app/+signup/+register/register-step-user.component.html
  client/src/app/+signup/+register/register-step-user.component.ts
  client/src/app/+signup/+register/register.component.html
  client/src/app/+signup/+register/register.component.scss
  client/src/app/+signup/+register/register.component.ts
  client/src/app/+signup/+register/register.module.ts
  client/src/app/shared/form-validators/user-validators.ts
  client/src/app/shared/shared-instance/index.ts
  client/src/app/shared/shared-instance/instance-about-accordion.component.html
  client/src/app/shared/shared-instance/instance-about-accordion.component.scss
  client/src/app/shared/shared-instance/instance-about-accordion.component.ts
  client/src/app/shared/shared-instance/shared-instance.module.ts
Labels: UI

#3406 Set canonical link to original video/playlist url
  server/lib/client-html.ts
  server/models/account/account.ts
  server/models/video/video-channel.ts
  server/tests/client.ts
  shared/extra-utils/server/servers.ts
Labels: Type: Bug :bug:

#3423 emit more specific status codes on video upload
  client/src/app/+about/about-instance/contact-admin-modal.component.ts
  client/src/app/+accounts/accounts.component.ts
  client/src/app/+my-library/+my-video-channels/my-video-channel-create.component.ts
  client/src/app/+video-channels/video-channels.component.ts
  client/src/app/+videos/+video-edit/video-add-components/video-upload.component.ts
  client/src/app/+videos/+video-watch/video-watch.component.ts
  client/src/app/core/auth/auth.service.ts
  client/src/app/core/rest/rest-extractor.service.ts
  client/src/standalone/videos/embed.ts
  server/controllers/client.ts
  server/controllers/static.ts
  server/helpers/custom-validators/misc.ts
  server/helpers/custom-validators/videos.ts
  server/helpers/youtube-dl.ts
  server/lib/activitypub/actor.ts
  server/lib/activitypub/playlist.ts
  server/lib/activitypub/videos.ts
  server/lib/client-html.ts
  server/middlewares/cache.ts
  server/middlewares/validators/videos/videos.ts
  server/tests/api/activitypub/client.ts
  server/tests/api/activitypub/refresher.ts
  server/tests/api/check-params/accounts.ts
  server/tests/api/check-params/contact-form.ts
  server/tests/api/check-params/users.ts
  server/tests/api/check-params/videos.ts
  server/tests/api/live/live-save-replay.ts
  server/tests/api/live/live.ts
  server/tests/api/server/config.ts
  server/tests/api/server/contact-form.ts
  server/tests/api/server/email.ts
  server/tests/api/server/follow-constraints.ts
  server/tests/api/server/handle-down.ts
  server/tests/api/server/no-client.ts
  server/tests/api/server/reverse-proxy.ts
  server/tests/api/videos/multiple-servers.ts
  server/tests/api/videos/video-change-ownership.ts
  server/tests/api/videos/video-hls.ts
  server/tests/api/videos/video-playlists.ts
  server/tests/api/videos/video-privacy.ts
  server/tests/api/videos/videos-history.ts
  server/tests/cli/reset-password.ts
  server/tests/feeds/feeds.ts
  server/tests/plugins/filter-hooks.ts
  server/tests/plugins/video-constants.ts
  server/tools/peertube-redundancy.ts
  shared/core-utils/miscs/http-error-codes.ts
  shared/extra-utils/server/activitypub.ts
  shared/extra-utils/server/redundancy.ts
  shared/extra-utils/users/login.ts
  shared/extra-utils/videos/video-history.ts
  shared/extra-utils/videos/videos.ts
  support/doc/api/openapi.yaml
Labels: Component: Documentation :books:

#3434 add info about hostname change
  support/doc/production.md
  support/doc/tools.md
Labels: Component: Documentation :books:

#3344 User dropdown and notifications popover improvements
  client/src/app/+my-account/my-account-notifications/my-account-notifications.component.html
  client/src/app/app.module.ts
  client/src/app/menu/index.ts
  client/src/app/menu/menu.component.html
  client/src/app/menu/menu.component.scss
  client/src/app/menu/menu.component.ts
  client/src/app/menu/notification.component.html
  client/src/app/menu/notification.component.scss
  client/src/app/menu/notification.component.ts
  client/src/app/shared/shared-icons/global-icon.component.ts
  client/src/assets/images/feather/bell.svg
  client/src/assets/images/feather/inbox-full.svg
Labels: UI
