Repository Chocobozzz/PeerTube, pull requests merged in 2020-06, with the labels that each got.

#2802 Make federation of unlisted videos an instance-level server preference
  config/default.yaml
  config/production.yaml.example
  server/helpers/video.ts
  server/initializers/checker-before-init.ts
  server/initializers/config.ts
  server/models/video/video.ts
  server/tests/api/videos/video-privacy.ts
Labels: Component: Federation :ferris_wheel:

#2832 Add lang attribute in languages list menu
  client/src/app/menu/language-chooser.component.html
  client/src/app/menu/language-chooser.component.ts
Labels: Component: i18n :abcd:

#2838 Add channel/account avatars in miniature
  client/src/app/shared/channel/avatar.component.html
  client/src/app/shared/channel/avatar.component.scss
  client/src/app/shared/channel/avatar.component.ts
  client/src/app/shared/video/abstract-video-list.ts
  client/src/app/shared/video/video-miniature.component.html
  client/src/app/shared/video/video-miniature.component.ts
  client/src/app/videos/recommendations/recommended-videos.component.html
  client/src/app/videos/recommendations/recommended-videos.component.ts
  client/src/assets/images/global/search.svg
  client/src/assets/images/menu/trending.svg
Labels: UI

#2844 add aria-hidden to non-descriptive icons
  client/src/app/+admin/follows/following-list/following-list.component.html
  client/src/app/+admin/moderation/instance-blocklist/instance-server-blocklist.component.html
  client/src/app/+admin/users/user-list/user-list.component.html
  client/src/app/+my-account/my-account-history/my-account-history.component.html
  client/src/app/+my-account/my-account-notifications/my-account-notifications.component.html
  client/src/app/+my-account/my-account-video-channels/my-account-video-channels.component.html
  client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.html
  client/src/app/+my-account/my-account-videos/my-account-videos.component.html
  client/src/app/header/header.component.html
  client/src/app/menu/avatar-notification.component.html
  client/src/app/menu/menu.component.html
  client/src/app/shared/buttons/delete-button.component.html
  client/src/app/shared/buttons/edit-button.component.html
  client/src/app/shared/users/user-notifications.component.html
  client/src/app/shared/video-playlist/video-add-to-playlist.component.html
  client/src/app/shared/video-playlist/video-playlist-element-miniature.component.html
  client/src/app/videos/+video-edit/shared/video-edit.component.html
  client/src/app/videos/+video-edit/video-add-components/video-import-torrent.component.html
  client/src/app/videos/+video-edit/video-add-components/video-import-url.component.html
  client/src/app/videos/+video-edit/video-add-components/video-upload.component.html
  client/src/app/videos/+video-edit/video-update.component.html
  client/src/app/videos/+video-watch/video-watch.component.html
Labels: Component: Accessibility, UI

#2845 change focus color instead of opacity of video play button
  client/src/app/menu/language-chooser.component.ts
  client/src/sass/player/peertube-skin.scss
Labels: Component: Accessibility, UI

#2866 add scope tags and aria-labels to instance table
  client/src/app/+about/about-instance/about-instance.component.html
  client/src/app/shared/instance/feature-boolean.component.html
  client/src/app/shared/instance/instance-features-table.component.html
  client/src/app/shared/instance/instance-features-table.component.scss
Labels: Component: Accessibility

#2854 add keyboard navigation for video actions
  client/src/app/+admin/plugins/plugin-search/plugin-search.component.html
  client/src/app/shared/buttons/action-dropdown.component.html
  client/src/app/shared/channel/avatar.component.scss
  client/src/app/shared/menu/top-menu-dropdown.component.html
  client/src/app/shared/users/user-notifications.component.html
  client/src/app/shared/video/abstract-video-list.html
  client/src/app/shared/video/video-miniature.component.html
  client/src/app/shared/video/video-miniature.component.scss
  client/src/app/videos/+video-edit/video-add-components/video-import-torrent.component.html
  client/src/app/videos/+video-edit/video-add-components/video-import-url.component.html
  client/src/app/videos/+video-edit/video-add-components/video-upload.component.html
  client/src/app/videos/+video-watch/video-watch.component.html
  client/src/sass/application.scss
Labels: Component: Accessibility, UI

#2868 fix opendkim permissions in docker-compose setup
  support/docker/production/.env
Labels: Component: Docker :whale:

#2871 fix headings order or add missing ones
  client/src/app/+about/about-follows/about-follows.component.html
  client/src/app/+about/about-instance/about-instance.component.html
  client/src/app/+about/about-instance/contact-admin-modal.component.html
  client/src/app/+about/about-peertube/about-peertube.component.html
  client/src/app/+about/about-peertube/about-peertube.component.scss
  client/src/app/+accounts/account-about/account-about.component.html
  client/src/app/+accounts/account-video-channels/account-video-channels.component.html
  client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html
  client/src/app/+admin/follows/follows.component.html
  client/src/app/+admin/moderation/moderation.component.html
  client/src/app/+admin/plugins/plugins.component.html
  client/src/app/+admin/system/system.component.html
  client/src/app/+admin/users/user-list/user-list.component.html
  client/src/app/+my-account/my-account-blocklist/my-account-blocklist.component.html
  client/src/app/+my-account/my-account-blocklist/my-account-server-blocklist.component.html
  client/src/app/+my-account/my-account-history/my-account-history.component.html
  client/src/app/+my-account/my-account-notifications/my-account-notifications.component.html
  client/src/app/+my-account/my-account-ownership/my-account-accept-ownership/my-account-accept-ownership.component.html
  client/src/app/+my-account/my-account-ownership/my-account-ownership.component.html
  client/src/app/+my-account/my-account-settings/my-account-settings.component.html
  client/src/app/+my-account/my-account-subscriptions/my-account-subscriptions.component.html
  client/src/app/+my-account/my-account-video-channels/my-account-video-channels.component.html
  client/src/app/+my-account/my-account-video-imports/my-account-video-imports.component.html
  client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.html
  client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.scss
  client/src/app/+my-account/my-account-videos/my-account-videos.component.html
  client/src/app/+my-account/my-account-videos/my-account-videos.component.scss
  client/src/app/+my-account/shared/actor-avatar-info.component.html
  client/src/app/shared/instance/instance-statistics.component.html
  client/src/app/shared/instance/instance-statistics.component.scss
  client/src/app/shared/video/abstract-video-list.html
  client/src/app/videos/+video-watch/comment/video-comments.component.html
  client/src/app/videos/recommendations/recommended-videos.component.html
  client/src/app/videos/video-list/video-overview.component.html
  client/src/sass/include/_miniature.scss
Labels: Component: Accessibility, UI

#2870 Logging ip requesting unknown infoHash
  server/controllers/tracker.ts
Labels: Type: Maintenance :construction_worker_woman:

#2879 Remove uneccessary details to link titles
  client/src/app/+admin/plugins/plugin-list-installed/plugin-list-installed.component.html
  client/src/app/+admin/plugins/plugin-search/plugin-search.component.html
  client/src/app/+my-account/my-account-ownership/my-account-ownership.component.html
  client/src/app/+my-account/my-account-subscriptions/my-account-subscriptions.component.html
  client/src/app/+my-account/my-account-video-channels/my-account-video-channels.component.html
  client/src/app/app.component.html
  client/src/app/menu/menu.component.html
  client/src/app/shared/channel/avatar.component.html
  client/src/app/shared/channel/avatar.component.ts
  client/src/app/shared/video/video-miniature.component.ts
  client/src/app/videos/+video-watch/video-watch.component.html
  client/src/assets/player/videojs-components/peertube-link-button.ts
Labels: Component: Accessibility, UI

#2842 predefined report reasons & improved reporter UI
  client/src/app/+admin/moderation/moderation.component.scss
  client/src/app/+admin/moderation/video-abuse-list/video-abuse-details.component.html
  client/src/app/+admin/moderation/video-abuse-list/video-abuse-details.component.ts
  client/src/app/+admin/moderation/video-abuse-list/video-abuse-list.component.ts
  client/src/app/shared/rest/rest.service.ts
  client/src/app/shared/video-abuse/video-abuse.service.ts
  client/src/app/shared/video/modals/video-block.component.html
  client/src/app/shared/video/modals/video-report.component.html
  client/src/app/shared/video/modals/video-report.component.scss
  client/src/app/shared/video/modals/video-report.component.ts
  client/src/app/shared/video/video.model.ts
  client/src/environments/environment.e2e.ts
  client/src/environments/environment.hmr.ts
  client/src/environments/environment.prod.ts
  client/src/environments/environment.ts
  client/src/sass/include/_mixins.scss
  client/src/sass/player/peertube-skin.scss
  server/controllers/api/videos/abuse.ts
  server/helpers/custom-validators/video-abuses.ts
  server/initializers/constants.ts
  server/initializers/migrations/0515-video-abuse-reason-timestamps.ts
  server/lib/activitypub/process/process-flag.ts
  server/middlewares/validators/videos/video-abuses.ts
  server/models/video/video-abuse.ts
  server/tests/api/check-params/video-abuses.ts
  server/tests/api/videos/video-abuse.ts
  shared/extra-utils/videos/video-abuses.ts
  shared/models/activitypub/activity.ts
  shared/models/activitypub/objects/common-objects.ts
  shared/models/activitypub/objects/video-abuse-object.ts
  shared/models/videos/abuse/video-abuse-create.model.ts
  shared/models/videos/abuse/video-abuse-reason.model.ts
  shared/models/videos/abuse/video-abuse.model.ts
  shared/models/videos/index.ts
  support/doc/api/openapi.yaml
Labels: Component: Federation :ferris_wheel:, Component: Moderation :godmode:, UI

#2896 link to third-party-application raw list in noscript
  client/src/index.html
Labels: Component: Documentation :books:
