Repository Chocobozzz/PeerTube, pull requests merged in 2021-03, with the labels that each got.

#3890 Show less information in download modal
  client/src/app/shared/shared-video-miniature/video-download.component.html
  client/src/app/shared/shared-video-miniature/video-download.component.scss
  client/src/app/shared/shared-video-miniature/video-download.component.ts
Labels: UI

#3899 Update dependencies.md for macOSX.
  support/doc/dependencies.md
Labels: Component: Documentation :books:

#3901 fix missing title attribute on <iframe> tag suggested for embedding
  client/src/app/+admin/moderation/video-block-list/video-block-list.component.ts
  client/src/app/+videos/+video-watch/video-watch.component.ts
  client/src/app/shared/shared-abuse-list/abuse-list-table.component.ts
  client/src/app/shared/shared-moderation/report-modals/video-report.component.ts
  client/src/app/shared/shared-share-modal/video-share.component.ts
  client/src/assets/player/peertube-player-manager.ts
  client/src/assets/player/utils.ts
  client/src/standalone/videos/embed.ts
  server/controllers/services.ts
  server/helpers/core-utils.ts
  server/lib/client-html.ts
  server/tests/api/server/services.ts
  shared/core-utils/renderer/html.ts
Labels: Component: Accessibility, Component: Embed
