Repository Chocobozzz/PeerTube, pull requests merged in 2021-06, with the labels that each got.

#4163 allow public video privacy to be deleted in the web client
  client/src/app/+videos/+video-edit/shared/video-edit.component.ts
  client/src/app/+videos/+video-edit/video-add-components/video-go-live.component.ts
  client/src/app/+videos/+video-edit/video-add-components/video-import-torrent.component.ts
  client/src/app/+videos/+video-edit/video-add-components/video-import-url.component.ts
  client/src/app/+videos/+video-edit/video-add-components/video-send.ts
  client/src/app/+videos/+video-edit/video-add-components/video-upload.component.ts
  client/src/app/shared/shared-main/video/video.service.ts
Labels: Type: Maintenance :construction_worker_woman:

#4126 add client hook filter:videojs.options
  client/src/app/+videos/+video-watch/video-watch.component.ts
  client/src/app/core/plugins/plugin.service.ts
  client/src/app/core/theme/theme.service.ts
  client/src/assets/player/peertube-player-manager.ts
  client/src/root-helpers/index.ts
  client/src/root-helpers/plugins-manager.ts
  client/src/root-helpers/plugins.ts
  client/src/standalone/videos/embed.ts
  shared/models/plugins/client/client-hook.model.ts
Labels: Status: Waiting for changes

#4181 Update CHANGELOG.md
  CHANGELOG.md
Labels: Component: Documentation :books:
