Repository Chocobozzz/PeerTube, pull requests merged in 2021-01, with the labels that each got.

#3538 client: add iOS icon
  client/src/index.html
Labels: Type: Enhancement :sparkles:, UI

#3563 Mark 'These settings apply only to' string as i18n-able
  client/src/app/modal/quick-settings-modal.component.html
Labels: Component: i18n :abcd:

#3467 add ability to remove one's avatar for account and channels
  client/src/app/+my-account/my-account-settings/my-account-settings.component.html
  client/src/app/+my-account/my-account-settings/my-account-settings.component.ts
  client/src/app/+my-library/+my-video-channels/my-video-channel-edit.component.html
  client/src/app/+my-library/+my-video-channels/my-video-channel-edit.ts
  client/src/app/+my-library/+my-video-channels/my-video-channel-update.component.ts
  client/src/app/core/users/user.model.ts
  client/src/app/core/users/user.service.ts
  client/src/app/shared/shared-main/account/account.model.ts
  client/src/app/shared/shared-main/account/actor-avatar-info.component.html
  client/src/app/shared/shared-main/account/actor-avatar-info.component.scss
  client/src/app/shared/shared-main/account/actor-avatar-info.component.ts
  client/src/app/shared/shared-main/video-channel/video-channel.model.ts
  client/src/app/shared/shared-main/video-channel/video-channel.service.ts
  client/src/sass/include/_mixins.scss
  server/controllers/api/users/me.ts
  server/controllers/api/video-channel.ts
  server/lib/activitypub/actor.ts
  server/lib/avatar.ts
Labels: Component: Channels, Status: Ready to Merge

#3518 add support for 1440p (Quad HD/QHD/WQHD) videos
  client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.ts
  config/default.yaml
  config/production.yaml.example
  config/test.yaml
  server/controllers/api/config.ts
  server/helpers/ffprobe-utils.ts
  server/initializers/checker-before-init.ts
  server/initializers/config.ts
  server/middlewares/validators/config.ts
  server/tests/api/check-params/config.ts
  server/tests/api/live/live-constraints.ts
  server/tests/api/live/live-permanent.ts
  server/tests/api/live/live-save-replay.ts
  server/tests/api/server/config.ts
  server/tests/api/server/stats.ts
  server/tests/api/videos/audio-only.ts
  server/tests/api/videos/video-hls.ts
  server/tests/cli/create-transcoding-job.ts
  shared/extra-utils/server/config.ts
  shared/models/server/custom-config.model.ts
  shared/models/videos/video-resolution.enum.ts
  support/doc/api/openapi.yaml
  support/docker/production/config/custom-environment-variables.yaml
Labels: Component: Transcoding, Status: Ready to Merge

#3550 Allow administrator to disable logging of ping requests
  config/default.yaml
  config/production.yaml.example
  server.ts
  server/initializers/config.ts
  support/docker/production/config/custom-environment-variables.yaml
Labels: Type: Enhancement :sparkles:, Type: Maintenance :construction_worker_woman:

#3564 show first decimal for views above a thousand
  client/src/app/shared/shared-main/angular/number-formatter.pipe.ts
Labels: Status: Ready to Merge, UI

#3576 Allow user to search through their watch history
  client/src/app/+my-library/my-history/my-history.component.html
  client/src/app/+my-library/my-history/my-history.component.scss
  client/src/app/+my-library/my-history/my-history.component.ts
  client/src/app/+my-library/my-subscriptions/my-subscriptions.component.html
  client/src/app/shared/shared-main/users/user-history.service.ts
  server/controllers/api/users/my-history.ts
  server/middlewares/validators/user-history.ts
  server/models/account/user-video-history.ts
  server/models/video/video.ts
  server/tests/api/videos/videos-history.ts
  shared/extra-utils/videos/video-history.ts
  support/doc/api/openapi.yaml
Labels: Component: Search, Status: Ready to Merge

#3577 higher priority for live transcoding compared to vod transcoding
  server/helpers/ffmpeg-utils.ts
  server/initializers/constants.ts
Labels: Component: Live, Component: Transcoding, Status: Ready to Merge

#3581 Mention additional nginx modules required since #3313
  support/nginx/peertube
Labels: Component: Documentation :books:, Status: Ready to Merge

#3598 Feature/remote interaction
  client/src/app/+remote-interaction/remote-interaction-routing.module.ts
  client/src/app/+remote-interaction/remote-interaction.component.html
  client/src/app/+remote-interaction/remote-interaction.component.scss
  client/src/app/+remote-interaction/remote-interaction.component.ts
  client/src/app/+remote-interaction/remote-interaction.module.ts
  client/src/app/+videos/+video-watch/comment/video-comment-add.component.html
  client/src/app/app-routing.module.ts
  client/src/app/core/routing/redirect.service.ts
  client/src/app/shared/form-validators/user-validators.ts
  client/src/app/shared/shared-user-subscription/remote-subscribe.component.html
  client/src/app/shared/shared-user-subscription/remote-subscribe.component.ts
  client/src/app/shared/shared-user-subscription/subscribe-button.component.html
  server/controllers/webfinger.ts
  server/tests/misc-endpoints.ts
Labels: Component: Federation :ferris_wheel:

#3516 stricter youtubedl format selectors
  client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html
  client/src/app/+my-library/my-video-imports/my-video-imports.component.html
  server/controllers/api/config.ts
  server/controllers/api/videos/import.ts
  server/controllers/static.ts
  server/helpers/youtube-dl.ts
  server/lib/job-queue/handlers/video-import.ts
  server/lib/video-transcoding.ts
  server/middlewares/validators/videos/video-imports.ts
  server/tests/api/videos/video-imports.ts
  server/tests/api/videos/video-transcoder.ts
  server/tools/peertube-import-videos.ts
  shared/core-utils/miscs/http-error-codes.ts
  shared/extra-utils/videos/video-imports.ts
  shared/models/server/job.model.ts
Labels: Component: Import, Component: Transcoding

#3589 Allow users/visitors to search through an account's videos
  client/src/app/+accounts/account-search/account-search.component.ts
  client/src/app/+accounts/accounts-routing.module.ts
  client/src/app/+accounts/accounts.component.html
  client/src/app/+accounts/accounts.component.ts
  client/src/app/+accounts/accounts.module.ts
  client/src/app/shared/shared-main/misc/index.ts
  client/src/app/shared/shared-main/misc/simple-search-input.component.html
  client/src/app/shared/shared-main/misc/simple-search-input.component.scss
  client/src/app/shared/shared-main/misc/simple-search-input.component.ts
  client/src/app/shared/shared-main/shared-main.module.ts
  client/src/app/shared/shared-main/video/video.service.ts
  client/src/sass/include/_mixins.scss
  server/controllers/api/accounts.ts
  server/middlewares/validators/videos/videos.ts
  server/tests/api/users/users-multiple-servers.ts
  shared/extra-utils/videos/videos.ts
Labels: Component: Search

#3635 prettify SQL queries during debug
  package.json
  server/helpers/logger.ts
  server/initializers/database.ts
  yarn.lock
Labels: Status: Waiting for changes, Type: Maintenance :construction_worker_woman:

#3489 add `proxy_ignore_client_abort` flag to Nginx conf
  support/nginx/peertube
Labels: Type: Maintenance :construction_worker_woman:

#3643 localize decimal separator in video miniatures
  client/src/app/shared/shared-main/angular/number-formatter.pipe.ts
  client/src/app/shared/shared-video-miniature/video-download.component.ts
Labels: Component: i18n :abcd:
