Repository Chocobozzz/PeerTube, pull requests merged in 2021-04, with the labels that each got.

#3920 remove unnecessary black border above and below video in player
  client/src/app/+videos/+video-watch/video-watch.component.scss
Labels: Component: Player :play_or_pause_button:, UI

#3927 Reducing tag input excessive padding; fixes #3915
  client/src/sass/ng-select.scss
Labels: UI

#3909 Don't pause video upon modal open
  .gitignore
  client/src/app/+videos/+video-watch/video-watch.component.html
  client/src/app/+videos/+video-watch/video-watch.component.ts
Labels: Component: Player :play_or_pause_button:, UI

#3946 Add `i18n` prop where it is missing
  client/src/app/+admin/follows/followers-list/followers-list.component.html
  client/src/app/+admin/follows/following-list/following-list.component.html
  client/src/app/+admin/follows/video-redundancies-list/video-redundancies-list.component.html
  client/src/app/+admin/moderation/video-comment-list/video-comment-list.component.html
  client/src/app/+admin/system/debug/debug.component.html
  client/src/app/shared/shared-moderation/account-blocklist.component.html
  client/src/app/shared/shared-moderation/server-blocklist.component.html
Labels: Component: i18n :abcd:

#3950 fix localization on page not found
  client/src/app/+page-not-found/page-not-found.component.html
  client/src/app/+page-not-found/page-not-found.component.ts
Labels: Component: i18n :abcd:

#3949 add loop toggle to the player contextmenu
  client/package.json
  client/src/assets/player/peertube-player-manager.ts
  client/yarn.lock
Labels: Component: Player :play_or_pause_button:

#3945 add link to open video on origin instance
  client/src/app/+videos/+video-watch/video-watch.component.html
  client/src/app/+videos/+video-watch/video-watch.component.ts
Labels: Component: Federation :ferris_wheel:, UI

#3963 Update VideoFile structure in the API doc
  support/doc/api/openapi.yaml
Labels: Component: Documentation :books:

#3984 rephrase signup limit validator error
  client/src/app/shared/form-validators/custom-config-validators.ts
Labels: Component: Documentation :books:

#3974 Added "last" and a reversed ?playlistPosition in playlist URL
  client/src/app/+videos/+video-watch/video-watch-playlist.component.ts
  client/src/app/+videos/+video-watch/video-watch.component.ts
Labels: Component: Playlist

#4002 Use account initial as default avatar
  client/src/app/+admin/users/user-list/user-list.component.html
  client/src/app/shared/shared-account-avatar/account-avatar.component.html
  client/src/app/shared/shared-account-avatar/account-avatar.component.scss
  client/src/app/shared/shared-account-avatar/account-avatar.component.ts
  client/src/app/shared/shared-main/account/account.model.ts
  client/src/sass/include/_mixins.scss
Labels: Component: Channels, UI
