Repository Chocobozzz/PeerTube, pull requests merged in 2021-02, with the labels that each got.

#3684 Rewrite prose for JavaScript disabled message
  client/src/index.html
  client/src/sass/application.scss
Labels: Type: Maintenance :construction_worker_woman:

#3693 Update production guide for certbot instructions
  support/doc/production.md
Labels: Component: Documentation :books:

#3726 Remove vips dependency from FreeBSD instructions
  support/doc/dependencies.md
Labels: Component: Documentation :books:

#3702 Tighten hotkeys definitions
  client/src/assets/player/peertube-player-manager.ts
Labels: Component: Player :play_or_pause_button:
